hw4_dbt:
  target: prod         # <--- this is your active target
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: de-zoomcamp-2026-486900
      dataset: dbt_dev
      threads: 1

    prod:
      type: bigquery
      method: oauth
      project: de-zoomcamp-2026-486900
      dataset: dbt_prod   # your production dataset
      threads: 1