# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19aX9nkdK-S1iV_WnUVRQBXpNTGvCgj-r
"""

!pip install "dlt[duckdb]"

import dlt
from dlt.sources.helpers.rest_client import RESTClient

@dlt.resource(name="rides", write_disposition="replace")
def taxi_rides():
    client = RESTClient(base_url="https://us-central1-dlthub-analytics.cloudfunctions.net")

    page = 1
    prev_first_id = None

    while True:
        # Requesting by page instead of offset
        params = {
            "page": page,
            "limit": 1000
        }
        response = client.get("data_engineering_zoomcamp_api", params=params)
        data = response.json()

        # 1. Stop if empty
        if not data:
            print(f"Stopped: No data on page {page}")
            break

        # 2. Check for duplication (The "Loop Trap")
        current_first_id = data[0].get('Trip_Pickup_DateTime') # Using timestamp as a proxy ID
        if prev_first_id == current_first_id:
            print(f"\n⚠️ Page {page} returned the same data as Page {page-1}.")
            print("The API does not support page-based pagination.")
            break

        print(f"✅ Loaded Page {page} ({len(data)} records)")
        yield data

        prev_first_id = current_first_id
        page += 1

pipeline = dlt.pipeline(pipeline_name="taxi_page_test", destination="duckdb", dataset_name="taxi_data")
pipeline.run(taxi_rides())

import duckdb

# Connect to the database created in your last run
conn = duckdb.connect("taxi_page_test.duckdb")

# Execute the final calculation
res = conn.execute("""
    SELECT
        COUNT(*) AS total_records,
        MIN(trip_pickup_date_time) AS start_time,
        MAX(trip_pickup_date_time) AS end_time,
        (COUNT(CASE WHEN payment_type = 'Credit' THEN 1 END) * 100.0 / COUNT(*)) AS credit_card_percentage,
        SUM(tip_amt) AS total_tips
    FROM taxi_data.rides
""").fetchone()

print("="*40)
print("🚕 FINAL HOMEWORK ANSWERS 🚕")
print("="*40)
print(f"Total Records: {res[0]}")
print(f"Q1 Date Range: {res[1]} to {res[2]}")
print(f"Q2 CC %:      {res[3]:.2f}%")
print(f"Q3 Total Tips: ${res[4]:,.2f}")
print("="*40)